// Copyright 2025 Beijing Volcano Engine Technology Co., Ltd. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Table related type definitions
 * Used to unify all table scenarios
 */

import type React from 'react';

/**
 * Base record value union type
 * Supports all common data types, including nested objects and arrays
 */
export type BaseRecordValue =
  | string
  | number
  | boolean
  | null
  | undefined
  | Record<string, unknown>
  | Array<unknown>
  | BaseRecord
  | BaseRecord[]
  | unknown;

/**
 * Base record type
 * Adapts to all types generated by api-generate, no additional index signature needed
 */
export type BaseRecord = {
  _id?: string;
  id?: string | number;
  key?: string | number;
  [key: string]: BaseRecordValue;
};

/**
 * Base query type
 * Generic query constraint based on bam-service request types
 */
export type BaseQuery = Record<string, unknown>;

/**
 * Plugin context interface
 */
export interface PluginContext<
  RecordType extends BaseRecord = BaseRecord,
  QueryType extends BaseQuery = BaseQuery,
  PProps = Record<string, unknown>,
> {
  readonly props: PProps;
  readonly state: Record<string, unknown>;
  readonly helpers: Record<string, unknown>;
  plugins?: Record<string, unknown>;
}

/**
 * Plugin manager interface
 */
export interface PluginManager {
  context?: PluginContext;
  plugins: Map<string, unknown>;
  metrics: Record<string, unknown>;
}

/**
 * Table data source interface
 */
export interface TableDataSource<
  RecordType extends BaseRecord = BaseRecord,
  QueryParams extends Record<string, unknown> = Record<string, unknown>,
> {
  /** Service instance */
  serviceInstance?: unknown;
  /** Service method name */
  serviceMethod?: string | symbol | number;
  /** Request function */
  request?: (params: QueryParams) => Promise<unknown>;
  /** Additional request parameters */
  payload?: Record<string, unknown>;
  /** Response data items key name */
  responseItemsKey?: string;
  /** Whether it's server-side pagination */
  isServerPagination?: boolean;
  /** Whether to filter empty columns */
  isEmptyColumnsFilter?: boolean;
  /** Whether the request can be cancelled */
  isCancel?: boolean;
  /** Whether it's ready */
  ready?: boolean;
  /** Whether it's manually triggered */
  manual?: boolean;
  /** Whether to continue */
  needContinue?: boolean;
  /** Whether there's more data */
  hasMoreData?: boolean;
  /** Data list */
  data?: RecordType[];
  /** Total count */
  total?: number;
  /** Loading state */
  loading?: boolean;
  /** Error message */
  error?: Error | null;
}

/**
 * Table action function types
 */
export interface TableActions<T = Record<string, unknown>> {
  /** Edit action */
  onEdit?: (record: T) => Promise<boolean>;
  /** Delete action */
  onDelete?: (id: string) => Promise<boolean>;
  /** Create action */
  onCreate?: () => Promise<boolean>;
  /** View action */
  onView?: (record: T) => void;
  /** View detail action */
  onViewDetail?: (record: T) => void;
  /** Retry action */
  onRetry?: (recordId: string) => void;
  /** Other custom actions */
  customActions?: (record: T) => React.ReactNode;
}

/**
 * Table data request response
 */
export interface TableDataResponse<T = Record<string, unknown>> {
  /** Data list */
  data: T[];
  /** Total count */
  total: number;
  /** Whether successful */
  success: boolean;
}

/**
 * Table response data type alias
 * @deprecated Please use TableDataResponse
 */
export type TableResponseData<T = Record<string, unknown>> =
  TableDataResponse<T>;

/**
 * First parameter type of render function
 * Usually the cell value, type depends on the column's dataIndex
 */
export type CellValue<T, K extends keyof T> = T[K];
/**
 * Table render function type
 */
export type TableRenderFunction<T, K extends keyof T = keyof T> = (
  value: CellValue<T, K>,
  record: T,
  index: number,
) => React.ReactNode;
