// Copyright 2025 Beijing Volcano Engine Technology Co., Ltd. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Shared type definitions
 * Used to avoid circular dependencies
 */
import type { ColumnProps as ArcoColumnProps } from '@arco-design/web-react/es/Table/interface';
import type { ReactNode } from 'react';

/**
 * Union type for base record values
 * Supports all common data types, including nested objects and arrays
 * Uses unknown as fallback type to ensure maximum compatibility
 */
export type BaseRecordValue =
  | string
  | number
  | boolean
  | null
  | undefined
  | Record<string, unknown>
  | Array<unknown>
  | BaseRecord
  | BaseRecord[]
  | unknown;

/**
 * Base record type
 * Compatible with all types generated by api-generate, no additional index signature needed
 */
export type BaseRecord = {
  _id?: string;
  id?: string | number;
  key?: string | number;
  [key: string]: BaseRecordValue;
};

/**
 * Modern table column type (for new plugin system)
 */
export interface ModernTableColumnProps<RecordType = BaseRecord>
  extends ArcoColumnProps<RecordType> {
  hidden?: boolean;
  tooltip?: string;
  copyable?: boolean;
  customRender?: (
    value: unknown,
    record: RecordType,
    index: number,
  ) => ReactNode;
}
