// Copyright 2025 Beijing Volcano Engine Technology Co., Ltd. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* generated using openapi-typescript-codegen -- do not edit */
export { VolcAIOpsApi } from './volc-ai-ops-api';

export { ApiError } from './core/api-error';
export { BaseHttpRequest } from './core/base-http-request';
export { FetchHttpRequest } from './core/fetch-http-request';
export { CancelablePromise, CancelError } from './core/cancelable-promise';
export type { OnCancel } from './core/cancelable-promise';
export { OpenAPI } from './core/open-api';
export type { OpenAPIConfig } from './core/open-api';
export type { ApiRequestOptions } from './core/api-request-options';

export type { AgentCfg } from './models/agent-cfg';
export type { AgentCfgPayload } from './models/agent-cfg-payload';
export type { AgentNotification } from './models/agent-notification';
export type { AgentTemplate } from './models/agent-template';
export type { AgentTemplateCreateRequest } from './models/agent-template-create-request';
export type { AgentTemplateUpdateRequest } from './models/agent-template-update-request';
export { AgentType } from './models/agent-type';
export type { AliyunContactGroup } from './models/aliyun-contact-group';
export type { AliyunDataSource } from './models/aliyun-data-source';
export type { AliyunDataSourceConfig } from './models/aliyun-data-source-config';
export type { AliyunMetric } from './models/aliyun-metric';
export type { AliyunMetricConfig } from './models/aliyun-metric-config';
export type { AliyunMetricMetaListPayload } from './models/aliyun-metric-meta-list-payload';
export type { AliyunProjectMetaPayload } from './models/aliyun-project-meta-payload';
export type { APIResponse } from './models/api-response';
export type { APIResponseAgentTemplate } from './models/api-response-agent-template';
export type { APIResponseBoolean } from './models/api-response-boolean';
export type { APIResponseBot } from './models/api-response-bot';
export type { APIResponseBotAttribute } from './models/api-response-bot-attribute';
export type { APIResponseBotAttributeList } from './models/api-response-bot-attribute-list';
export type { APIResponseBotList } from './models/api-response-bot-list';
export type { APIResponseChat } from './models/api-response-chat';
export type { APIResponseConnect } from './models/api-response-connect';
export type { APIResponseCustomer } from './models/api-response-customer';
export type { APIResponseCustomerList } from './models/api-response-customer-list';
export type { APIResponseDataSource } from './models/api-response-data-source';
export type { APIResponseDataSourceList } from './models/api-response-data-source-list';
export type { APIResponseEvent } from './models/api-response-event';
export type { APIResponseGlobalConfig } from './models/api-response-global-config';
export type { APIResponseImportResult } from './models/api-response-import-result';
export type { APIResponseInformStrategy } from './models/api-response-inform-strategy';
export type { APIResponseIntelligentThresholdAlarm } from './models/api-response-intelligent-threshold-alarm';
export type { APIResponseIntelligentThresholdTask } from './models/api-response-intelligent-threshold-task';
export type { APIResponseIntelligentThresholdTaskDetail } from './models/api-response-intelligent-threshold-task-detail';
export type { APIResponseIntelligentThresholdTaskVersion } from './models/api-response-intelligent-threshold-task-version';
export type { APIResponseInterest } from './models/api-response-interest';
export type { APIResponseInterestList } from './models/api-response-interest-list';
export type { APIResponseLoginToken } from './models/api-response-login-token';
export type { APIResponseMetricTemplate } from './models/api-response-metric-template';
export type { APIResponseMetricTemplateList } from './models/api-response-metric-template-list';
export type { APIResponseOncallSchedule } from './models/api-response-oncall-schedule';
export type { APIResponseProduct } from './models/api-response-product';
export type { APIResponseProject } from './models/api-response-project';
export type { APIResponseString } from './models/api-response-string';
export type { APIResponseStringList } from './models/api-response-string-list';
export type { APIResponseSubscribeRelation } from './models/api-response-subscribe-relation';
export type { APIResponseSyncAlarmRulesResponse } from './models/api-response-sync-alarm-rules-response';
export type { APIResponseSystemStatistics } from './models/api-response-system-statistics';
export type { APIResponseUser } from './models/api-response-user';
export type { APIResponseValidateBotResult } from './models/api-response-validate-bot-result';
export type { APIResponseVolcengineMetricList } from './models/api-response-volcengine-metric-list';
export type { APIResponseVolcengineProductList } from './models/api-response-volcengine-product-list';
export type { APIResponseZabbixHostList } from './models/api-response-zabbix-host-list';
export type { APIResponseZabbixItemList } from './models/api-response-zabbix-item-list';
export type { APIResponseZabbixMediatypeList } from './models/api-response-zabbix-mediatype-list';
export type { APIResponseZabbixTemplateList } from './models/api-response-zabbix-template-list';
export type { APIResponseZabbixTemplateMetricList } from './models/api-response-zabbix-template-metric-list';
export type { APIResponseZabbixUserGroupList } from './models/api-response-zabbix-user-group-list';
export { AttributeItem } from './models/attribute-item';
export { AttributeKey } from './models/attribute-key';
export type { BaseTimeseriesRequestPayload } from './models/base-timeseries-request-payload';
export { Bot } from './models/bot';
export type { BotAttribute } from './models/bot-attribute';
export type { BotAttributeCreateRequest } from './models/bot-attribute-create-request';
export type { BotAttributePayload } from './models/bot-attribute-payload';
export type { BotAttributeUpdateRequest } from './models/bot-attribute-update-request';
export { BotCreateRequest } from './models/bot-create-request';
export type { BotUpdateRequest } from './models/bot-update-request';
export type { BotVO } from './models/bot-vo';
export type { ChannelMsg } from './models/channel-msg';
export { ChannelType } from './models/channel-type';
export { Chat } from './models/chat';
export type { ChatConfigUpdatePayload } from './models/chat-config-update-payload';
export { ChatCreateRequest } from './models/chat-create-request';
export type { ChatUpdateRequest } from './models/chat-update-request';
export type { Connect } from './models/connect';
export type { ConnectCreateRequest } from './models/connect-create-request';
export type { ConnectUpdateRequest } from './models/connect-update-request';
export { CreateDataSourceRequest } from './models/create-data-source-request';
export type { CreateProjectPayload } from './models/create-project-payload';
export type { Customer } from './models/customer';
export type { CustomerCreateRequest } from './models/customer-create-request';
export { DataSource } from './models/data-source';
export { DataSourceType } from './models/data-source-type';
export type { ErrorDetail } from './models/error-detail';
export type { Event } from './models/event';
export type { EventDetail } from './models/event-detail';
export { EventLevel } from './models/event-level';
export { EventShowStatus } from './models/event-show-status';
export { EventStatus } from './models/event-status';
export type { GroupChatVO } from './models/group-chat-vo';
export { ImportLog } from './models/import-log';
export type { ImportResult } from './models/import-result';
export type { InformStrategy } from './models/inform-strategy';
export type { InformStrategyCreate } from './models/inform-strategy-create';
export type { InformStrategyUpdate } from './models/inform-strategy-update';
export { IntelligentThresholdAlarm } from './models/intelligent-threshold-alarm';
export { IntelligentThresholdAlarmCreateRequest } from './models/intelligent-threshold-alarm-create-request';
export type { IntelligentThresholdConfig } from './models/intelligent-threshold-config';
export { IntelligentThresholdTask } from './models/intelligent-threshold-task';
export { IntelligentThresholdTaskCreateRequest } from './models/intelligent-threshold-task-create-request';
export { IntelligentThresholdTaskDetail } from './models/intelligent-threshold-task-detail';
export { IntelligentThresholdTaskStatus } from './models/intelligent-threshold-task-status';
export { IntelligentThresholdTaskVersion } from './models/intelligent-threshold-task-version';
export { Interest } from './models/interest';
export { InterestCreateRequest } from './models/interest-create-request';
export { InterestUpdateRequest } from './models/interest-update-request';
export { ListIntelligentThresholdTaskRequest } from './models/list-intelligent-threshold-task-request';
export type { ListIntelligentThresholdTaskVersionRequest } from './models/list-intelligent-threshold-task-version-request';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { LoginToken } from './models/login-token';
export type { MetricTemplate } from './models/metric-template';
export type { MetricTemplateCreateRequest } from './models/metric-template-create-request';
export type { MetricTemplateUpdateRequest } from './models/metric-template-update-request';
export type { MetricTemplateValue } from './models/metric-template-value';
export type { MetricThresholdResult } from './models/metric-threshold-result';
export { MetricType } from './models/metric-type';
export { OncallSchedule } from './models/oncall-schedule';
export { OncallScheduleCreateRequest } from './models/oncall-schedule-create-request';
export type { OncallScheduleUpdateRequest } from './models/oncall-schedule-update-request';
export type { PaginatedAPIResponse } from './models/paginated-api-response';
export type { PaginatedAPIResponseAgentTemplateList } from './models/paginated-api-response-agent-template-list';
export type { PaginatedAPIResponseAliyunContactGroupList } from './models/paginated-api-response-aliyun-contact-group-list';
export type { PaginatedAPIResponseAliyunMetricList } from './models/paginated-api-response-aliyun-metric-list';
export type { PaginatedAPIResponseBotAttributeList } from './models/paginated-api-response-bot-attribute-list';
export type { PaginatedAPIResponseChatList } from './models/paginated-api-response-chat-list';
export type { PaginatedAPIResponseConnectList } from './models/paginated-api-response-connect-list';
export type { PaginatedAPIResponseEventList } from './models/paginated-api-response-event-list';
export type { PaginatedAPIResponseInformStrategyList } from './models/paginated-api-response-inform-strategy-list';
export type { PaginatedAPIResponseIntelligentThresholdTask } from './models/paginated-api-response-intelligent-threshold-task';
export type { PaginatedAPIResponseIntelligentThresholdTaskVersion } from './models/paginated-api-response-intelligent-threshold-task-version';
export type { PaginatedAPIResponseMetricTemplateList } from './models/paginated-api-response-metric-template-list';
export type { PaginatedAPIResponseOncallScheduleList } from './models/paginated-api-response-oncall-schedule-list';
export type { PaginatedAPIResponseProductList } from './models/paginated-api-response-product-list';
export type { PaginatedAPIResponseProjectList } from './models/paginated-api-response-project-list';
export type { PaginatedAPIResponseSubscribeRelationList } from './models/paginated-api-response-subscribe-relation-list';
export type { PaginatedAPIResponseUserList } from './models/paginated-api-response-user-list';
export type { PaginationMeta } from './models/pagination-meta';
export type { PaginationParams } from './models/pagination-params';
export type { PaginationRequest } from './models/pagination-request';
export type { Product } from './models/product';
export type { ProductCreateRequest } from './models/product-create-request';
export type { Project } from './models/project';
export type { ProjectCreateRequest } from './models/project-create-request';
export type { RefreshTokenRequest } from './models/refresh-token-request';
export { RerunIntelligentThresholdTaskRequest } from './models/rerun-intelligent-threshold-task-request';
export type { SortColumn } from './models/sort-column';
export type { SubscribeRelationCreate } from './models/subscribe-relation-create';
export type { SubscribeRelationUpdate } from './models/subscribe-relation-update';
export type { SubscribeRelationWithAttributes } from './models/subscribe-relation-with-attributes';
export { SyncAlarmRulesPayload } from './models/sync-alarm-rules-payload';
export type { SyncAlarmRulesResponse } from './models/sync-alarm-rules-response';
export type { SystemStatistics } from './models/system-statistics';
export type { TimeRange } from './models/time-range';
export type { ToggleActiveRequest } from './models/toggle-active-request';
export type { UpdateAutoRefreshSwitchPayload } from './models/update-auto-refresh-switch-payload';
export type { UpdateDataSourceRequest } from './models/update-data-source-request';
export type { UpdatePasswordRequest } from './models/update-password-request';
export { UpdateTaskResultRequest } from './models/update-task-result-request';
export type { User } from './models/user';
export type { UserCreateRequest } from './models/user-create-request';
export type { UserUpdateRequest } from './models/user-update-request';
export { ValidateBotRequest } from './models/validate-bot-request';
export type { ValidateBotResult } from './models/validate-bot-result';
export type { ValidationError } from './models/validation-error';
export type { VolcCfg } from './models/volc-cfg';
export { VolcCfgPayload } from './models/volc-cfg-payload';
export type { VolcengineDataSource } from './models/volcengine-data-source';
export type { VolcengineDataSourceConfig } from './models/volcengine-data-source-config';
export type { VolcengineMetric } from './models/volcengine-metric';
export type { VolcengineMetricConfig } from './models/volcengine-metric-config';
export type { VolcengineProduct } from './models/volcengine-product';
export type { ZabbixDataSource } from './models/zabbix-data-source';
export type { ZabbixDataSourceConfig } from './models/zabbix-data-source-config';
export type { ZabbixHost } from './models/zabbix-host';
export type { ZabbixItem } from './models/zabbix-item';
export type { ZabbixMediatype } from './models/zabbix-mediatype';
export type { ZabbixTarget } from './models/zabbix-target';
export type { ZabbixTemplate } from './models/zabbix-template';
export type { ZabbixTemplateMetric } from './models/zabbix-template-metric';
export type { ZabbixTriggerTag } from './models/zabbix-trigger-tag';
export type { ZabbixUserGroup } from './models/zabbix-user-group';

export { AgentTemplateService } from './services/agent-template-service';
export { AuthenticationService } from './services/authentication-service';
export { BotAttributesService } from './services/bot-attributes-service';
export { BotsService } from './services/bots-service';
export { ChatsService } from './services/chats-service';
export { CustomersService } from './services/customers-service';
export { DataSourceConnectService } from './services/data-source-connect-service';
export { DataSourcesService } from './services/data-sources-service';
export { EventService } from './services/event-service';
export { GlobalConfigService } from './services/global-config-service';
export { InformStrategyService } from './services/inform-strategy-service';
export { IntelligentThresholdAlarmService } from './services/intelligent-threshold-alarm-service';
export { IntelligentThresholdTaskService } from './services/intelligent-threshold-task-service';
export { MetricTemplateService } from './services/metric-template-service';
export { OncallRuleService } from './services/oncall-rule-service';
export { OncallScheduleService } from './services/oncall-schedule-service';
export { ProductsService } from './services/products-service';
export { ProjectsService } from './services/projects-service';
export { StatisticsService } from './services/statistics-service';
export { SubscribeService } from './services/subscribe-service';
export { UsersService } from './services/users-service';
export { WebhookService } from './services/webhook-service';
export { ZabbixService } from './services/zabbix-service';
